/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AfterchainRegistry__factory } from "./AfterchainRegistry__factory";
export { AfterchainWill__factory } from "./AfterchainWill__factory";
