/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace AfterchainWill {
  export type BeneficiaryStruct = {
    wallet: AddressLike;
    percentage: BigNumberish;
    label: string;
  };

  export type BeneficiaryStructOutput = [
    wallet: string,
    percentage: bigint,
    label: string
  ] & { wallet: string; percentage: bigint; label: string };
}

export interface AfterchainWillInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "beneficiaries"
      | "executeWill"
      | "executeWillTokens"
      | "executed"
      | "getBeneficiaries"
      | "getWillStatus"
      | "heartbeat"
      | "heartbeatInterval"
      | "lastHeartbeat"
      | "owner"
      | "updateWill"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EthDistributed"
      | "HeartbeatSent"
      | "TokenDistributed"
      | "WillExecuted"
      | "WillFunded"
      | "WillUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "beneficiaries",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executeWill",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executeWillTokens",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "executed", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getBeneficiaries",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getWillStatus",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "heartbeat", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "heartbeatInterval",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastHeartbeat",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateWill",
    values: [AfterchainWill.BeneficiaryStruct[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "beneficiaries",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeWill",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeWillTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "executed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBeneficiaries",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWillStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "heartbeat", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "heartbeatInterval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastHeartbeat",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "updateWill", data: BytesLike): Result;
}

export namespace EthDistributedEvent {
  export type InputTuple = [beneficiary: AddressLike, amount: BigNumberish];
  export type OutputTuple = [beneficiary: string, amount: bigint];
  export interface OutputObject {
    beneficiary: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HeartbeatSentEvent {
  export type InputTuple = [owner: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [owner: string, timestamp: bigint];
  export interface OutputObject {
    owner: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenDistributedEvent {
  export type InputTuple = [
    token: AddressLike,
    beneficiary: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    token: string,
    beneficiary: string,
    amount: bigint
  ];
  export interface OutputObject {
    token: string;
    beneficiary: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WillExecutedEvent {
  export type InputTuple = [executor: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [executor: string, timestamp: bigint];
  export interface OutputObject {
    executor: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WillFundedEvent {
  export type InputTuple = [sender: AddressLike, amount: BigNumberish];
  export type OutputTuple = [sender: string, amount: bigint];
  export interface OutputObject {
    sender: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WillUpdatedEvent {
  export type InputTuple = [owner: AddressLike, beneficiaryCount: BigNumberish];
  export type OutputTuple = [owner: string, beneficiaryCount: bigint];
  export interface OutputObject {
    owner: string;
    beneficiaryCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AfterchainWill extends BaseContract {
  connect(runner?: ContractRunner | null): AfterchainWill;
  waitForDeployment(): Promise<this>;

  interface: AfterchainWillInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  beneficiaries: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string] & {
        wallet: string;
        percentage: bigint;
        label: string;
      }
    ],
    "view"
  >;

  executeWill: TypedContractMethod<[], [void], "nonpayable">;

  executeWillTokens: TypedContractMethod<
    [tokenAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  executed: TypedContractMethod<[], [boolean], "view">;

  getBeneficiaries: TypedContractMethod<
    [],
    [AfterchainWill.BeneficiaryStructOutput[]],
    "view"
  >;

  getWillStatus: TypedContractMethod<
    [],
    [
      [boolean, bigint, bigint] & {
        _executed: boolean;
        _lastHeartbeat: bigint;
        _daysRemaining: bigint;
      }
    ],
    "view"
  >;

  heartbeat: TypedContractMethod<[], [void], "nonpayable">;

  heartbeatInterval: TypedContractMethod<[], [bigint], "view">;

  lastHeartbeat: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  updateWill: TypedContractMethod<
    [_beneficiaries: AfterchainWill.BeneficiaryStruct[]],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "beneficiaries"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string] & {
        wallet: string;
        percentage: bigint;
        label: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "executeWill"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "executeWillTokens"
  ): TypedContractMethod<[tokenAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "executed"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "getBeneficiaries"
  ): TypedContractMethod<
    [],
    [AfterchainWill.BeneficiaryStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getWillStatus"
  ): TypedContractMethod<
    [],
    [
      [boolean, bigint, bigint] & {
        _executed: boolean;
        _lastHeartbeat: bigint;
        _daysRemaining: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "heartbeat"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "heartbeatInterval"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lastHeartbeat"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "updateWill"
  ): TypedContractMethod<
    [_beneficiaries: AfterchainWill.BeneficiaryStruct[]],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "EthDistributed"
  ): TypedContractEvent<
    EthDistributedEvent.InputTuple,
    EthDistributedEvent.OutputTuple,
    EthDistributedEvent.OutputObject
  >;
  getEvent(
    key: "HeartbeatSent"
  ): TypedContractEvent<
    HeartbeatSentEvent.InputTuple,
    HeartbeatSentEvent.OutputTuple,
    HeartbeatSentEvent.OutputObject
  >;
  getEvent(
    key: "TokenDistributed"
  ): TypedContractEvent<
    TokenDistributedEvent.InputTuple,
    TokenDistributedEvent.OutputTuple,
    TokenDistributedEvent.OutputObject
  >;
  getEvent(
    key: "WillExecuted"
  ): TypedContractEvent<
    WillExecutedEvent.InputTuple,
    WillExecutedEvent.OutputTuple,
    WillExecutedEvent.OutputObject
  >;
  getEvent(
    key: "WillFunded"
  ): TypedContractEvent<
    WillFundedEvent.InputTuple,
    WillFundedEvent.OutputTuple,
    WillFundedEvent.OutputObject
  >;
  getEvent(
    key: "WillUpdated"
  ): TypedContractEvent<
    WillUpdatedEvent.InputTuple,
    WillUpdatedEvent.OutputTuple,
    WillUpdatedEvent.OutputObject
  >;

  filters: {
    "EthDistributed(address,uint256)": TypedContractEvent<
      EthDistributedEvent.InputTuple,
      EthDistributedEvent.OutputTuple,
      EthDistributedEvent.OutputObject
    >;
    EthDistributed: TypedContractEvent<
      EthDistributedEvent.InputTuple,
      EthDistributedEvent.OutputTuple,
      EthDistributedEvent.OutputObject
    >;

    "HeartbeatSent(address,uint256)": TypedContractEvent<
      HeartbeatSentEvent.InputTuple,
      HeartbeatSentEvent.OutputTuple,
      HeartbeatSentEvent.OutputObject
    >;
    HeartbeatSent: TypedContractEvent<
      HeartbeatSentEvent.InputTuple,
      HeartbeatSentEvent.OutputTuple,
      HeartbeatSentEvent.OutputObject
    >;

    "TokenDistributed(address,address,uint256)": TypedContractEvent<
      TokenDistributedEvent.InputTuple,
      TokenDistributedEvent.OutputTuple,
      TokenDistributedEvent.OutputObject
    >;
    TokenDistributed: TypedContractEvent<
      TokenDistributedEvent.InputTuple,
      TokenDistributedEvent.OutputTuple,
      TokenDistributedEvent.OutputObject
    >;

    "WillExecuted(address,uint256)": TypedContractEvent<
      WillExecutedEvent.InputTuple,
      WillExecutedEvent.OutputTuple,
      WillExecutedEvent.OutputObject
    >;
    WillExecuted: TypedContractEvent<
      WillExecutedEvent.InputTuple,
      WillExecutedEvent.OutputTuple,
      WillExecutedEvent.OutputObject
    >;

    "WillFunded(address,uint256)": TypedContractEvent<
      WillFundedEvent.InputTuple,
      WillFundedEvent.OutputTuple,
      WillFundedEvent.OutputObject
    >;
    WillFunded: TypedContractEvent<
      WillFundedEvent.InputTuple,
      WillFundedEvent.OutputTuple,
      WillFundedEvent.OutputObject
    >;

    "WillUpdated(address,uint256)": TypedContractEvent<
      WillUpdatedEvent.InputTuple,
      WillUpdatedEvent.OutputTuple,
      WillUpdatedEvent.OutputObject
    >;
    WillUpdated: TypedContractEvent<
      WillUpdatedEvent.InputTuple,
      WillUpdatedEvent.OutputTuple,
      WillUpdatedEvent.OutputObject
    >;
  };
}
