/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace AfterchainWill {
  export type BeneficiaryStruct = {
    wallet: AddressLike;
    percentage: BigNumberish;
    label: string;
  };

  export type BeneficiaryStructOutput = [
    wallet: string,
    percentage: bigint,
    label: string
  ] & { wallet: string; percentage: bigint; label: string };
}

export interface AfterchainRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "allWills"
      | "deployWill"
      | "getAllWills"
      | "getTotalWills"
      | "getWill"
      | "ownerToWill"
      | "registerWill"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "WillDeployed" | "WillRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "allWills",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deployWill",
    values: [BigNumberish, AfterchainWill.BeneficiaryStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllWills",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalWills",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getWill",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ownerToWill",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerWill",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "allWills", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deployWill", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllWills",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalWills",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getWill", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ownerToWill",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerWill",
    data: BytesLike
  ): Result;
}

export namespace WillDeployedEvent {
  export type InputTuple = [
    owner: AddressLike,
    willContract: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    owner: string,
    willContract: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    owner: string;
    willContract: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WillRegisteredEvent {
  export type InputTuple = [
    owner: AddressLike,
    willContract: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    owner: string,
    willContract: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    owner: string;
    willContract: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AfterchainRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): AfterchainRegistry;
  waitForDeployment(): Promise<this>;

  interface: AfterchainRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  allWills: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  deployWill: TypedContractMethod<
    [
      heartbeatIntervalDays: BigNumberish,
      beneficiaries: AfterchainWill.BeneficiaryStruct[]
    ],
    [string],
    "nonpayable"
  >;

  getAllWills: TypedContractMethod<[], [string[]], "view">;

  getTotalWills: TypedContractMethod<[], [bigint], "view">;

  getWill: TypedContractMethod<[owner: AddressLike], [string], "view">;

  ownerToWill: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  registerWill: TypedContractMethod<
    [willContract: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "allWills"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "deployWill"
  ): TypedContractMethod<
    [
      heartbeatIntervalDays: BigNumberish,
      beneficiaries: AfterchainWill.BeneficiaryStruct[]
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAllWills"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getTotalWills"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getWill"
  ): TypedContractMethod<[owner: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "ownerToWill"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "registerWill"
  ): TypedContractMethod<[willContract: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "WillDeployed"
  ): TypedContractEvent<
    WillDeployedEvent.InputTuple,
    WillDeployedEvent.OutputTuple,
    WillDeployedEvent.OutputObject
  >;
  getEvent(
    key: "WillRegistered"
  ): TypedContractEvent<
    WillRegisteredEvent.InputTuple,
    WillRegisteredEvent.OutputTuple,
    WillRegisteredEvent.OutputObject
  >;

  filters: {
    "WillDeployed(address,address,uint256)": TypedContractEvent<
      WillDeployedEvent.InputTuple,
      WillDeployedEvent.OutputTuple,
      WillDeployedEvent.OutputObject
    >;
    WillDeployed: TypedContractEvent<
      WillDeployedEvent.InputTuple,
      WillDeployedEvent.OutputTuple,
      WillDeployedEvent.OutputObject
    >;

    "WillRegistered(address,address,uint256)": TypedContractEvent<
      WillRegisteredEvent.InputTuple,
      WillRegisteredEvent.OutputTuple,
      WillRegisteredEvent.OutputObject
    >;
    WillRegistered: TypedContractEvent<
      WillRegisteredEvent.InputTuple,
      WillRegisteredEvent.OutputTuple,
      WillRegisteredEvent.OutputObject
    >;
  };
}
